# Generated by Django 2.2.5 on 2019-09-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinect', '0002_auto_20190910_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempo',
            name='tempo',
            field=models.TextField(),
        ),
    ]
