# Generated by Django 2.2.5 on 2019-10-01 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinect', '0003_auto_20190920_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessao',
            name='paciente',
        ),
    ]
